# PR Title Validation
# ====================
# Enforces conventional commit format on PR titles.
# Since we use squash merge, the PR title becomes the commit message.
#
# This workflow is inherited by all repos in the org.
#
# Valid formats:
#   feat: add new feature
#   fix(scope): resolve bug
#   feat!: breaking change
#   docs: update readme
#
# Valid types: feat, fix, docs, refactor, perf, test, chore, ci
# (These 8 types map to labels - see labels.yml)

name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-title:
    name: Validate PR Title
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title format
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;

            // Conventional commit regex
            // Matches: type(scope)!: subject or type!: subject or type: subject
            const pattern = /^(feat|fix|docs|refactor|perf|test|chore|ci)(\([a-z0-9-]+\))?!?:\s.+$/;

            console.log(`PR Title: "${title}"`);

            if (pattern.test(title)) {
              console.log('✅ PR title follows conventional commit format');
              return;
            }

            // Title doesn't match - provide helpful error
            const errorMessage = `## ❌ PR Title Check Failed

Your PR title doesn't follow the required format.

**Your title:** \`${title}\`

**Required format:** \`<type>(<scope>): <subject>\`

### Valid Types

| Type | Use When | Example |
|------|----------|---------|
| \`feat\` | New feature | \`feat: add wallet connection\` |
| \`fix\` | Bug fix | \`fix(api): resolve timeout\` |
| \`docs\` | Documentation | \`docs: update readme\` |
| \`refactor\` | Code restructuring | \`refactor: simplify auth\` |
| \`perf\` | Performance | \`perf: optimize queries\` |
| \`test\` | Tests | \`test: add unit tests\` |
| \`chore\` | Maintenance | \`chore: update deps\` |
| \`ci\` | CI/CD | \`ci: add workflow\` |

### Breaking Changes

Add \`!\` before the colon: \`feat!: change API\`

### Rules

- Type must be lowercase
- Scope is optional, must be lowercase
- Subject must not start with uppercase
- Subject must not end with period
- Max 100 characters total

### Examples

✅ \`feat: add user authentication\`
✅ \`fix(auth): resolve token refresh\`
✅ \`feat!: change response format\`
✅ \`chore: update dependencies\`

❌ \`Add new feature\` (missing type)
❌ \`Feat: add feature\` (uppercase type)
❌ \`feat: Add feature.\` (uppercase subject, period)

---

📚 [Labels reference](https://github.com/altworth-markets/.github/blob/main/labels.yml)`;

            // Post or update comment
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              per_page: 100
            });

            const botComment = comments.data.find(c =>
              c.user?.login === 'github-actions[bot]' &&
              c.body?.includes('PR Title Check Failed')
            );

            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: errorMessage
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: errorMessage
              });
            }

            core.setFailed('PR title must follow conventional commit format');

      - name: Remove outdated comment on success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            // Remove any previous failure comments if title is now valid
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              per_page: 100
            });

            const botComment = comments.data.find(c =>
              c.user?.login === 'github-actions[bot]' &&
              c.body?.includes('PR Title Check Failed')
            );

            if (botComment) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id
              });
              console.log('Removed outdated PR title failure comment');
            }
